// <auto-generated />
namespace De_Tutjes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Kristofmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Kristofmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201705081751362_Kristof migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
